services:
  db:
    image: postgres:16.1
    container_name: db
    env_file:
      - .env
    user: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./fixtures/init-db-postgres.sql:/docker-entrypoint-initdb.d/init.sql
      - zip_service-pg:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      zip_service-network:

volumes:
  zip_service-pg:

networks:
  zip_service-network:
    name: zip_service-network